name: Trigger Azure Data Factory Deployment

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy-adf:
    name: Deploy Azure Data Factory
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        ref: adf_publish # Replace <BRANCH_NAME> with the branch containing the desired files

    - name: Export Azure Credentials
      run: |
        name: Configure Azure credentials
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_JSON }}

    - name: Extract credentials and set environment variables
      run: |
        echo "${{ secrets.AZURE_CREDENTIALS_JSON }}" > credentials.json
        export ARM_CLIENT_ID=$(python -c 'import json,sys;obj=json.load(open("credentials.json"));print(obj["clientId"])')
        export ARM_CLIENT_SECRET=$(python -c 'import json,sys;obj=json.load(open("credentials.json"));print(obj["clientSecret"])')
        export ARM_TENANT_ID=$(python -c 'import json,sys;obj=json.load(open("credentials.json"));print(obj["tenantId"])')
        export ARM_SUBSCRIPTION_ID=$(python -c 'import json,sys;obj=json.load(open("credentials.json"));print(obj["subscriptionId"])')

    - name: Login to Azure
      run: |
        az login --service-principal \
        --username=$ARM_CLIENT_ID \
        --password=$ARM_CLIENT_SECRET \
        --tenant=$ARM_TENANT_ID
          

    - name: Deploy Data Factory ARM Templates
      run: |
        az deployment group create \
          --resource-group POC \
          --template-file EtlDataFactoryPoc1/ARMTemplateForFactory.json \
          --parameters EtlDataFactoryPoc1/ARMTemplateParametersForFactory.json

    - name: Confirm Deployment
      run: |
        echo "Deployment to Azure Data Factory completed successfully!"
